set(INSTALL_ROOT nightfire-open)

set(TARGETNAME_INCLUDES_SDK sdk_includes)
set(TARGETNAME_INCLUDES_FILESYSTEM filesystem_includes)
set(TARGETNAME_INCLUDES_ENGINE engine_includes)

set(TARGETNAME_LIB_PUBLIC public)
set(TARGETNAME_LIB_FILESYSTEM_STDIO filesystem_stdio)
set(TARGETNAME_LIB_REF_SOFT ref_soft)
set(TARGETNAME_LIB_ENGINE xash)

set(TARGETNAME_EXE_GAME_LAUNCHER bond)
